insert into public.django_content_type (id, app_label, model)
values  (1, 'admin', 'logentry'),
        (2, 'auth', 'permission'),
        (3, 'auth', 'group'),
        (4, 'auth', 'user'),
        (5, 'contenttypes', 'contenttype'),
        (6, 'sessions', 'session'),
        (7, 'shop', 'authgroup'),
        (8, 'shop', 'authgrouppermissions'),
        (9, 'shop', 'authpermission'),
        (10, 'shop', 'authuser'),
        (11, 'shop', 'authusergroups'),
        (12, 'shop', 'authuseruserpermissions'),
        (13, 'shop', 'djangocontenttype'),
        (14, 'shop', 'djangomigrations'),
        (15, 'shop', 'djangosession'),
        (16, 'shop', 'djangoadminlog'),
        (17, 'shop', 'product'),
        (18, 'shop', 'order'),
        (19, 'shop', 'review');