insert into public.auth_permission (id, name, content_type_id, codename)
values  (1, 'Can add log entry', 1, 'add_logentry'),
        (2, 'Can change log entry', 1, 'change_logentry'),
        (3, 'Can delete log entry', 1, 'delete_logentry'),
        (4, 'Can view log entry', 1, 'view_logentry'),
        (5, 'Can add permission', 2, 'add_permission'),
        (6, 'Can change permission', 2, 'change_permission'),
        (7, 'Can delete permission', 2, 'delete_permission'),
        (8, 'Can view permission', 2, 'view_permission'),
        (9, 'Can add group', 3, 'add_group'),
        (10, 'Can change group', 3, 'change_group'),
        (11, 'Can delete group', 3, 'delete_group'),
        (12, 'Can view group', 3, 'view_group'),
        (13, 'Can add user', 4, 'add_user'),
        (14, 'Can change user', 4, 'change_user'),
        (15, 'Can delete user', 4, 'delete_user'),
        (16, 'Can view user', 4, 'view_user'),
        (17, 'Can add content type', 5, 'add_contenttype'),
        (18, 'Can change content type', 5, 'change_contenttype'),
        (19, 'Can delete content type', 5, 'delete_contenttype'),
        (20, 'Can view content type', 5, 'view_contenttype'),
        (21, 'Can add session', 6, 'add_session'),
        (22, 'Can change session', 6, 'change_session'),
        (23, 'Can delete session', 6, 'delete_session'),
        (24, 'Can view session', 6, 'view_session'),
        (25, 'Can add auth group', 7, 'add_authgroup'),
        (26, 'Can change auth group', 7, 'change_authgroup'),
        (27, 'Can delete auth group', 7, 'delete_authgroup'),
        (28, 'Can view auth group', 7, 'view_authgroup'),
        (29, 'Can add auth group permissions', 8, 'add_authgrouppermissions'),
        (30, 'Can change auth group permissions', 8, 'change_authgrouppermissions'),
        (31, 'Can delete auth group permissions', 8, 'delete_authgrouppermissions'),
        (32, 'Can view auth group permissions', 8, 'view_authgrouppermissions'),
        (33, 'Can add auth permission', 9, 'add_authpermission'),
        (34, 'Can change auth permission', 9, 'change_authpermission'),
        (35, 'Can delete auth permission', 9, 'delete_authpermission'),
        (36, 'Can view auth permission', 9, 'view_authpermission'),
        (37, 'Can add auth user', 10, 'add_authuser'),
        (38, 'Can change auth user', 10, 'change_authuser'),
        (39, 'Can delete auth user', 10, 'delete_authuser'),
        (40, 'Can view auth user', 10, 'view_authuser'),
        (41, 'Can add auth user groups', 11, 'add_authusergroups'),
        (42, 'Can change auth user groups', 11, 'change_authusergroups'),
        (43, 'Can delete auth user groups', 11, 'delete_authusergroups'),
        (44, 'Can view auth user groups', 11, 'view_authusergroups'),
        (45, 'Can add auth user user permissions', 12, 'add_authuseruserpermissions'),
        (46, 'Can change auth user user permissions', 12, 'change_authuseruserpermissions'),
        (47, 'Can delete auth user user permissions', 12, 'delete_authuseruserpermissions'),
        (48, 'Can view auth user user permissions', 12, 'view_authuseruserpermissions'),
        (49, 'Can add django content type', 13, 'add_djangocontenttype'),
        (50, 'Can change django content type', 13, 'change_djangocontenttype'),
        (51, 'Can delete django content type', 13, 'delete_djangocontenttype'),
        (52, 'Can view django content type', 13, 'view_djangocontenttype'),
        (53, 'Can add django migrations', 14, 'add_djangomigrations'),
        (54, 'Can change django migrations', 14, 'change_djangomigrations'),
        (55, 'Can delete django migrations', 14, 'delete_djangomigrations'),
        (56, 'Can view django migrations', 14, 'view_djangomigrations'),
        (57, 'Can add django session', 15, 'add_djangosession'),
        (58, 'Can change django session', 15, 'change_djangosession'),
        (59, 'Can delete django session', 15, 'delete_djangosession'),
        (60, 'Can view django session', 15, 'view_djangosession'),
        (61, 'Can add django admin log', 16, 'add_djangoadminlog'),
        (62, 'Can change django admin log', 16, 'change_djangoadminlog'),
        (63, 'Can delete django admin log', 16, 'delete_djangoadminlog'),
        (64, 'Can view django admin log', 16, 'view_djangoadminlog'),
        (65, 'Can add product', 17, 'add_product'),
        (66, 'Can change product', 17, 'change_product'),
        (67, 'Can delete product', 17, 'delete_product'),
        (68, 'Can view product', 17, 'view_product'),
        (69, 'Can add order', 18, 'add_order'),
        (70, 'Can change order', 18, 'change_order'),
        (71, 'Can delete order', 18, 'delete_order'),
        (72, 'Can view order', 18, 'view_order'),
        (73, 'Can add review', 19, 'add_review'),
        (74, 'Can change review', 19, 'change_review'),
        (75, 'Can delete review', 19, 'delete_review'),
        (76, 'Can view review', 19, 'view_review');