version: '2'
name: proj-bazy
services:  
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - proj-bazy
volumes:
  db-data:
networks:
  proj-bazy:
    driver: bridge